import { EmptyState } from "@/components/empty-state";
import { MarkdownSurface } from "@/components/markdown-surface";
import { PageShell } from "@/components/page-shell";
import { getConfig } from "@/lib/config";
import { getRoadmapData } from "@/server/view-models/roadmap";

export default async function RoadmapPage() {
  const cfg = getConfig();
  const roadmap = await getRoadmapData(cfg.projectRoot);

  const sources = (
    <p>
      Reads <code>ROADMAP.md</code> from the project root, generated by{" "}
      <code>/roadmap</code> (roadmap-cartographer agent).
    </p>
  );

  return (
    <PageShell
      title="Roadmap"
      // TODO: thread artifact mtime through the view-model for the "data as of" stamp
      sourcesContent={sources}
    >
      <p className="page-intro__lede muted">
        Project-level direction and backlog, rendered directly from{" "}
        <code>ROADMAP.md</code>.
      </p>

      {!roadmap ? (
        <EmptyState
          title="No roadmap present"
          body="Generate `ROADMAP.md` for the target project to surface long-horizon direction here."
        />
      ) : (
        <article className="artifact-card">
          <MarkdownSurface body={roadmap.body} />
        </article>
      )}
    </PageShell>
  );
}
