#!/usr/bin/env python3
"""Reject AI-authorship trailers in a commit message (a `commit-msg` gate).

Rule enforced: `rules/swe/vcs/git-conventions.md` § Commit Message Format and
`rules/swe/agent-behavioral-contract.md` -- *the human owns the commit*, so no
`Co-Authored-By: Claude ...` trailer and no `Generated with [Claude Code]` badge
may ship. Subagents receive a session-level instruction presenting exactly such
a trailer as mandated and resolve the conflict in favour of that framing; the
repo's prose prohibition loses that contest every time it is not mechanical.

Measured cost that motivated the gate (td-196): two of 21 commits on the
process-economy-p2-1 pipeline shipped a trailer and needed amending, and a third
spawn complied only after its prompt carried an explicit override clause. Until
this gate, enforcement was "the orchestrator noticing" -- the shape dec-378 rules
out as a guard.

Golden bad-cases (each is a finding; the canary is
`scripts/test_check_commit_msg_authorship.py`)::

    Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>
    🤖 Generated with [Claude Code](https://claude.com/claude-code)
    Generated by Claude

Declared limits -- accepted false negatives, deliberately, so the two patterns
stay anchored rather than growing a vendor list:

- a trailer naming another vendor's model (`Co-Authored-By: GPT-5 <bot@openai.com>`)
- a badge line that names neither Claude nor Anthropic
- a trailer smuggled into a `#` comment line (git strips those before the
  message is stored, so they never reach the history this gate protects)

Accepted, by design: a human co-author (`Co-Authored-By: Jane Doe <jane@x.io>`),
and the words "Claude", "Anthropic" or "generated" anywhere in subject or body
prose -- only trailer-shaped lines and the generated-with badge line match.

Usage (pre-commit, `stages: [commit-msg]`, the message file is the argument)::

    python3 scripts/check_commit_msg_authorship.py .git/COMMIT_EDITMSG

Exit 1 naming each offending line when any pattern matches; exit 0 otherwise.
Stdlib only: this runs under whatever interpreter pre-commit resolves.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# One anchored pattern per shape. Both are case-insensitive and require the
# Claude/Anthropic name on the same line, so prose mentions elsewhere never fire.
_AI_TRAILER = re.compile(r"^\s*Co-Authored-By:.*\b(claude|anthropic)\b", re.IGNORECASE)
_AI_BADGE = re.compile(
    r"^\s*(?:\S+\s+)?Generated\s+(?:with|by)\b.*\b(claude|anthropic)\b", re.IGNORECASE
)

_PATTERNS = (("ai-co-author-trailer", _AI_TRAILER), ("ai-generated-badge", _AI_BADGE))


def check_commit_message(text: str) -> list[dict]:
    """Return one finding per line that carries an AI-authorship trailer or badge.

    Comment lines are skipped the way git's `cleanup=strip` drops them, so the
    template text pre-commit and git leave in the editor never trips the gate.
    """
    findings: list[dict] = []
    for lineno, line in enumerate(text.splitlines(), 1):
        if line.lstrip().startswith("#"):
            continue
        for name, pattern in _PATTERNS:
            if pattern.search(line):
                findings.append({"check": name, "line": lineno, "text": line.strip()})
                break
    return findings


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if len(args) != 1:
        print("usage: check_commit_msg_authorship.py <commit-message-file>", file=sys.stderr)
        return 2
    text = Path(args[0]).read_text(encoding="utf-8", errors="replace")
    findings = check_commit_message(text)
    if not findings:
        return 0
    print(
        "check_commit_msg_authorship: the human owns the commit -- remove the "
        "AI-authorship line(s) below (rules/swe/vcs/git-conventions.md):",
        file=sys.stderr,
    )
    for f in findings:
        print(f"  line {f['line']} [{f['check']}]: {f['text']}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
