from __future__ import annotations

import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
INSTALLER = REPO_ROOT / "install_codex.sh"


def run_install(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [str(INSTALLER), *args],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def test_install_codex_exports_canonical_paths_and_check_passes(tmp_path: Path):
    project_dir = tmp_path / "project"
    project_dir.mkdir()

    install = run_install(str(project_dir))
    assert install.returncode == 0, install.stderr or install.stdout

    researcher = (project_dir / ".codex" / "agents" / "researcher.toml").read_text(encoding="utf-8")
    planning = (project_dir / ".agents" / "skills" / "software-planning" / "SKILL.md").read_text(
        encoding="utf-8"
    )
    command = (project_dir / ".agents" / "skills" / "praxion-command-co" / "SKILL.md").read_text(
        encoding="utf-8"
    )

    assert str((REPO_ROOT / "agents" / "researcher.md").resolve()).replace("\\", "/") in researcher
    assert str((REPO_ROOT / "skills" / "software-planning" / "SKILL.md").resolve()).replace("\\", "/") in planning
    assert str((REPO_ROOT / "commands" / "co.md").resolve()).replace("\\", "/") in command
    assert "Treat any user text after the command name as `$ARGUMENTS`." in command
    assert (project_dir / ".codex" / "praxion" / "rules_manifest.json").exists()
    assert (project_dir / ".codex" / "hooks.json").exists()
    config_text = (project_dir / ".codex" / "config.toml").read_text(encoding="utf-8")
    assert "hooks = true" in config_text
    assert "codex_hooks" not in config_text

    check = run_install(str(project_dir), "--check")
    assert check.returncode == 0, check.stderr or check.stdout


def test_install_codex_check_fails_on_unexpected_generated_wrappers(tmp_path: Path):
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    install = run_install(str(project_dir))
    assert install.returncode == 0, install.stderr or install.stdout

    fake_agent = project_dir / ".codex" / "agents" / "fake-agent.toml"
    fake_agent.write_text(
        "# Generated by Praxion Codex exporter.\nname = \"fake-agent\"\ndescription = \"bogus\"\n",
        encoding="utf-8",
    )
    fake_skill_dir = project_dir / ".agents" / "skills" / "fake-skill"
    fake_skill_dir.mkdir(parents=True)
    (fake_skill_dir / "SKILL.md").write_text(
        "---\nname: fake-skill\ndescription: 'bogus'\n---\n\nThis is a Codex skill wrapper for Praxion.\n",
        encoding="utf-8",
    )
    fake_command_dir = project_dir / ".agents" / "skills" / "praxion-command-fake"
    fake_command_dir.mkdir(parents=True)
    (fake_command_dir / "SKILL.md").write_text(
        "---\nname: praxion-command-fake\ndescription: 'bogus'\n---\n\n"
        "This is a Codex command-skill wrapper for a Praxion slash command.\n",
        encoding="utf-8",
    )

    check = run_install(str(project_dir), "--check")
    assert check.returncode == 1
    assert "Unexpected stale Praxion agent wrapper" in check.stdout
    assert "Unexpected stale Praxion skill wrapper" in check.stdout


def test_install_codex_reinstall_prunes_unexpected_generated_wrappers(tmp_path: Path):
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    install = run_install(str(project_dir))
    assert install.returncode == 0, install.stderr or install.stdout

    fake_agent = project_dir / ".codex" / "agents" / "fake-agent.toml"
    fake_agent.write_text(
        "# Generated by Praxion Codex exporter.\nname = \"fake-agent\"\ndescription = \"bogus\"\n",
        encoding="utf-8",
    )
    fake_skill_dir = project_dir / ".agents" / "skills" / "fake-skill"
    fake_skill_dir.mkdir(parents=True)
    fake_skill = fake_skill_dir / "SKILL.md"
    fake_skill.write_text(
        "---\nname: fake-skill\ndescription: 'bogus'\n---\n\nThis is a Codex skill wrapper for Praxion.\n",
        encoding="utf-8",
    )
    fake_command_dir = project_dir / ".agents" / "skills" / "praxion-command-fake"
    fake_command_dir.mkdir(parents=True)
    fake_command = fake_command_dir / "SKILL.md"
    fake_command.write_text(
        "---\nname: praxion-command-fake\ndescription: 'bogus'\n---\n\n"
        "This is a Codex command-skill wrapper for a Praxion slash command.\n",
        encoding="utf-8",
    )

    reinstall = run_install(str(project_dir))
    assert reinstall.returncode == 0, reinstall.stderr or reinstall.stdout
    assert not fake_agent.exists()
    assert not fake_skill.exists()
    assert not fake_command.exists()


def test_install_codex_uninstall_preserves_user_codex_config_and_hooks(tmp_path: Path):
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    codex_dir = project_dir / ".codex"
    codex_dir.mkdir()
    (codex_dir / "config.toml").write_text(
        '[features]\nother_flag = true\nhooks = false\ncodex_hooks = false\n',
        encoding="utf-8",
    )
    (codex_dir / "hooks.json").write_text(
        '{\n  "hooks": {\n    "SessionStart": [\n      {\n        "hooks": [\n          {\n            "type": "command",\n            "command": "python3 user-hook.py",\n            "statusMessage": "User hook"\n          }\n        ]\n      }\n    ]\n  }\n}\n',
        encoding="utf-8",
    )

    install = run_install(str(project_dir))
    assert install.returncode == 0, install.stderr or install.stdout

    installed_config = (codex_dir / "config.toml").read_text(encoding="utf-8")
    assert "other_flag = true" in installed_config
    assert "hooks = true" in installed_config
    assert "codex_hooks" not in installed_config
    hooks_text = (codex_dir / "hooks.json").read_text(encoding="utf-8")
    assert "python3 user-hook.py" in hooks_text
    assert "praxion-session-start.py" in hooks_text

    uninstall = run_install(str(project_dir), "--uninstall")
    assert uninstall.returncode == 0, uninstall.stderr or uninstall.stdout

    final_config = (codex_dir / "config.toml").read_text(encoding="utf-8")
    assert "other_flag = true" in final_config
    assert "hooks = false" in final_config
    assert "codex_hooks = false" in final_config
    final_hooks = (codex_dir / "hooks.json").read_text(encoding="utf-8")
    assert "python3 user-hook.py" in final_hooks
    assert "praxion-session-start.py" not in final_hooks
    assert not (codex_dir / "praxion" / "config_state.json").exists()
