from __future__ import annotations

import importlib.util
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
EXPORTER_PATH = REPO_ROOT / "codex" / "config" / "export-codex-agents.py"


def load_exporter():
    spec = importlib.util.spec_from_file_location("export_codex_agents", EXPORTER_PATH)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_export_agents_writes_required_codex_fields(tmp_path: Path):
    exporter = load_exporter()
    out_dir = tmp_path / "agents"

    written = exporter.export_agents(REPO_ROOT, out_dir)

    assert written
    researcher = out_dir / "researcher.toml"
    assert researcher in written
    text = researcher.read_text(encoding="utf-8")
    assert text.startswith("# Generated by Praxion Codex exporter.\n")
    assert 'name = "researcher"' in text
    assert "description =" in text
    assert "developer_instructions =" in text
    assert (
        str((REPO_ROOT / "agents" / "researcher.md").resolve()).replace("\\", "/")
        in text
    )
    assert "source file remains authoritative" in text
    assert "Surface Assumptions" in text
    developer_instructions = text.split("developer_instructions =", maxsplit=1)[1]
    assert "You do not implement." not in developer_instructions


def test_export_agents_translates_routing_and_keeps_contract_capsule(tmp_path: Path):
    exporter = load_exporter()
    out_dir = tmp_path / "agents"

    exporter.export_agents(REPO_ROOT, out_dir)

    researcher = (out_dir / "researcher.toml").read_text(encoding="utf-8")
    promethean = (out_dir / "promethean.toml").read_text(encoding="utf-8")

    assert 'model = "gpt-5.4"' in researcher
    assert 'model_reasoning_effort = "medium"' in researcher
    assert "Praxion agent contract:" in researcher

    assert 'model = "gpt-5.5"' in promethean
    assert 'model_reasoning_effort = "high"' in promethean
    assert (
        "tools: Read, Glob, Grep, Bash, Write, Edit, AskUserQuestion, WebFetch"
        in promethean
    )
    assert "permissionMode: default" in promethean
    assert "hooks:" in promethean
    assert "async: true" in promethean
    assert "Do not duplicate the canonical agent body here." in promethean
    assert (
        str((REPO_ROOT / "agents" / "promethean.md").resolve()).replace("\\", "/")
        in promethean
    )


def test_parse_rejects_missing_frontmatter(tmp_path: Path):
    exporter = load_exporter()
    path = tmp_path / "bad.md"
    path.write_text("No frontmatter\n", encoding="utf-8")

    try:
        exporter.parse_frontmatter_agent(path)
    except exporter.AgentParseError as exc:
        assert "missing YAML frontmatter" in str(exc)
    else:
        raise AssertionError("expected AgentParseError")
