"""Canary for `check_commit_msg_authorship.py` (td-196): the golden bad-cases fire,
the accepted shapes pass, and the exit code carries the verdict."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_commit_msg_authorship import check_commit_message, main  # noqa: E402

_TRAILER = "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>"
_BADGE = "🤖 Generated with [Claude Code](https://claude.com/claude-code)"


def test_ai_co_author_trailer_is_rejected():
    findings = check_commit_message(f"feat: thing\n\n{_TRAILER}\n")
    assert [f["check"] for f in findings] == ["ai-co-author-trailer"]
    assert findings[0]["line"] == 3


@pytest.mark.parametrize(
    "line",
    [
        _BADGE,
        "Generated by Claude",
        "generated with claude code",
        "Co-authored-by: claude <bot@example.com>",
        "  Co-Authored-By: Anthropic Claude",
    ],
)
def test_each_golden_bad_case_is_rejected(line):
    assert check_commit_message(f"fix: x\n\n{line}\n"), line


def test_human_trailer_and_prose_mentions_pass():
    msg = (
        "feat: mention Claude in prose\n\n"
        "The body says this was generated with help and names Anthropic; that is prose.\n"
        "Co-Authored-By: Jane Doe <jane@example.com>\n"
        "Signed-off-by: Jane Doe <jane@example.com>\n"
    )
    assert check_commit_message(msg) == []


def test_comment_lines_are_ignored_like_git_strips_them():
    msg = f"fix: x\n\n# {_TRAILER}\n#\t{_BADGE}\n"
    assert check_commit_message(msg) == []


def test_main_exit_code_is_nonzero_on_a_finding(tmp_path, capsys):
    good = tmp_path / "good.txt"
    good.write_text("chore: fine\n", encoding="utf-8")
    bad = tmp_path / "bad.txt"
    bad.write_text(f"chore: bad\n\n{_TRAILER}\n{_BADGE}\n", encoding="utf-8")

    assert main([str(good)]) == 0
    assert main([str(bad)]) == 1
    err = capsys.readouterr().err
    assert "line 3 [ai-co-author-trailer]" in err
    assert "line 4 [ai-generated-badge]" in err
    assert main([]) == 2
